#ifndef BTN_DEF
#define BTN_DEF(BTN_NAME, BTN_GPIO)
#endif

BTN_DEF(BTN_ROT_R, GPIO_NUM_34)
BTN_DEF(BTN_ROT_L, GPIO_NUM_35)
BTN_DEF(BTN_SOUND, GPIO_NUM_32)
BTN_DEF(BTN_START, GPIO_NUM_33)
BTN_DEF(BTN_ONOFF, GPIO_NUM_25)
BTN_DEF(BTN_R, GPIO_NUM_26)
BTN_DEF(BTN_L, GPIO_NUM_27)
BTN_DEF(BTN_D, GPIO_NUM_14)
BTN_DEF(BTN_U, GPIO_NUM_12)